# ref: https://github.com/actions/runner-images
name: amd64 MacOS

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    name: MacOS•.Net
    runs-on: macos-13 # latest intel based macos runner
    steps:
      - uses: actions/checkout@v5
      - name: Check dotnet
        run: dotnet --info
      - name: Build
        run: dotnet build -c Release
      - name: Test
        run: dotnet run -c Release
      - name: Pack
        run: dotnet pack -c Release
