# ref: https://github.com/docker-library/official-images
name: amd64 Docker

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      matrix:
        #platform: [amd64, arm64, riscv64]
        platform: [amd64]
        distro: [
          almalinux,
          archlinux,
          debian,
          fedora,
          opensuse,
          rockylinux,
          ubuntu
        ]
      fail-fast: false
    name: ${{matrix.platform}}•${{matrix.distro}}•.Net
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check docker
        run: |
          docker info
          docker buildx ls
      - name: Build env image
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_env
      - name: Build devel image
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_devel
      - name: Build project
        run: make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_build
      - name: Run project
        run: VERBOSE=1 make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_run
      - name: Pack project
        run: VERBOSE=1 make --directory=ci ${{matrix.platform}}_${{matrix.distro}}_pack

  amd64_docker_dotnet:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - uses: actions/checkout@v4
